# This is a basic workflow to help you get started with Actions

name: c-linter

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  c-linter:
    name: c-linter
    runs-on: ubuntu-latest
    steps:
      - name: c-linter
        uses: ArtificialAmateur/cpp-linter-action@0.01
    env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
