name: Makefile CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: submodule
      run: git submodule update --init
      
    - name: Install dependencies
      run: sudo apt-get install xorriso lld
      
    - name: Build
      run: make 

