name: Makefile CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      
    - name: Install dependencies
      run: sudo apt-get install xorriso
      
    - name: Clean
      run: make distclean
    
    - name: Toolchain
      run: source ./toolchain/setup.sh
      
    - name: Build
      run: make -j2

